/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cvb6c5CEXE4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Newsreader } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

newsreader({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import { Button } from "@/components/ui/button"
import { FontSizeIcon } from "@radix-ui/react-icons";
import Link from "next/link"
// import fundoLogo from '../../assets/fundo-logo.png';

export function V0page() {
  return (<>
    <section
      className="relative w-full h-[80vh] flex items-center justify-center bg-cover bg-center"
      style={{
        backgroundImage: `url(/fundo-logo.png)`,
      }}>
      <div className="absolute inset-0 bg-gray-900/70" />
      <div
        className="relative z-10 text-center text-white max-w-3xl px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">AwA</h1>
        <p className="mt-6 text-lg leading-8">
          Uma maneira mais lúdica e interativa de aprender.🎮📕🧩
        </p>
        <div className="mt-10 flex items-center justify-center gap-x-6">
          <Link href="https://github.com/Fabio-Mnte/Amazon-Hacking-AWA/releases/tag/beta_1.2" target="_blank">
            <Button>Jogue Agora</Button>
          </Link>
          <Link
            className="text-sm font-semibold leading-6 text-white hover:text-gray-300"
            href="https://linktr.ee/edu_awa" target="_blank">
            Saiba Mais!
          </Link>
        </div>
      </div>
    </section>
    <section className="py-20 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 mx-auto sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md p-6">
            <LeafIcon className="h-12 w-12 text-green-500 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Sistema Educacional</h3>
            <p className="text-gray-600 dark:text-gray-400">
              Conte com elementos familiares da amazônia para garantir uma identificação mais rápida e eficaz com o conteúdo.
            </p>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md p-6">
            <GamepadIcon className="h-12 w-12 text-yellow-500 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Histórias</h3>
            <p className="text-gray-600 dark:text-gray-400">
              Como professor, personalize histórias e atividades para seus alunos, tornando o aprendizado customizado e não repetitivo.
            </p>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md p-6">
            <TrophyIcon className="h-12 w-12 text-blue-500 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Avaliação</h3>
            <p className="text-gray-600 dark:text-gray-400">
              Avalie o desempenho dos alunos para personalizar a dificuldade das atividades.
            </p>
          </div>
        </div>
      </div>
    </section>
    <section className="py-20 text-center">
      <div className="container px-4 mx-auto sm:px-6 lg:px-8 text-center">
        <h2 className="text-3xl font-bold mb-6">Afinal, qual o intuito disso?</h2>
        <p className="text-gray-600 dark:text-gray-400 mb-8">
          Com a pandemia, diversos alunos ficaram sem aulas e, olhando o contexto ao qual estavam encaixados, eles não tinham a opção de aulas online ou outros métodos de ensino,
          prejudicando de maneira grotesca a sua educação.
          
        </p>
        <p className="text-gray-600 dark:text-gray-400 mb-8">
          Pensando nisso, criamos o AwA, um jogo educacional que visa ensinar de forma lúdica e interativa, garantindo que o aluno aprenda de forma eficaz e divertida,
          onde, além de aprender, ele se diverte e interage com os colegas, já que existe a compatibilidade de utilizar mais de um controle para jogar.
        </p>
        <p className="text-gray-600 dark:text-gray-400 mb-8">
          Além disso, a criação de atividades e histórias é totalmente customizável pelo professor, garantindo que a turma receba atividades conforme o seu nível de aprendizado
          e evolução, mantendo um padrão alto de aprendizado e evitando a repetição de atividades.
        </p>
      </div>
    </section>
    <section className="text-center">
      <Link href="https://amazonhacking.com.br/pt/solutions/awa" target="_blank">
        <Button size="lg" style={{fontSize: '22px'}}>
          Vote na gente
        </Button>
      </Link>
    </section>
    <section className="py-20 text-center">
      <div className="container px-4 mx-auto sm:px-6 lg:px-8 text-center">
        <h2 className="text-3xl font-bold mb-6">Download do jogo</h2>
        <p className="text-gray-600 dark:text-gray-400 mb-8">
          Explore o código fonte do projeto e experimente enquanto ele ainda está em desenvolvimento.
        </p>
        <div className="flex justify-center gap-4">
          <Link href="https://github.com/Fabio-Mnte/Amazon-Hacking-AWA" target="_blank">
            <Button>
              <GithubIcon className="h-6 w-6 mr-2" />
              GitHub
            </Button>
          </Link>
        </div>
      </div>
    </section>
  </>);
}

function AppleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>)
  );
}


function ChromeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>)
  );
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
    </svg>
  );
}


function GamepadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="6" x2="10" y1="12" y2="12" />
      <line x1="8" x2="8" y1="10" y2="14" />
      <line x1="15" x2="15.01" y1="13" y2="13" />
      <line x1="18" x2="18.01" y1="11" y2="11" />
      <rect width="20" height="12" x="2" y="6" rx="2" />
    </svg>)
  );
}


function LeafIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>)
  );
}


function TrophyIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>)
  );
}
